version: "3.7"
services:
  node-app:
    container_name: api
    build: .
    depends_on:
      - postgres
    ports:
      - 3000:3000
    env_file:
      - ./.env
  #  mongo:
  #   image: mongo
  #   restart: always
  #  volumes:
  #      - mongo-db:/data/db
  #    environment:
  #      MONGO_INITDB_ROOT_USERNAME: root
  #      MONGO_INITDB_ROOT_PASSWORD: example
  #  mongo-express:
  #    image: mongo-express
  #    restart: always
  #    depends_on:
  #      - mongo
  #    ports:
  #      - 8081:8081
  #    environment:
  #      ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432" # Map port 5432 on the host to 5432 in the container
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - type: tmpfs
        target: /path/to/tmpfs
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: mydb # Include this to create the database on startup

  redis:
    image: redis
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
    ports:
      - "8080:80"
volumes:
  mongo-db:
  postgres-db:
